### ISSUE TITLE
Error when using a neural network inside a system of nonlinear equations.

### ISSUE THREAD

**Issue by GevikUCL** [SciML/NonlinearSolve.jl#114]
I've set up the following very simple system of nonlinear equations to solve.

```
using NonlinearSolve, Lux, LinearAlgebra, StableRNGs

rng = StableRNG(1111)

function func(u, p)
    [u[1].*u[1] .- p[1],
    u[2].*u[2] .- p[2]]
end

guess = [1., 1.]
params = [2.,3.]

prob = NonlinearProblem{false}(func, guess, params)
solution = solve(prob, NewtonRaphson())
```
This works fine. I am now trying to learn one of the terms from this system of equations using a neural network (similar to the UDE approach https://docs.sciml.ai/Overview/dev/showcase/missing_physics/).

I define a network.
```
ann = Lux.Chain(
    Lux.Dense(2,20,tanh), Lux.Dense(20,20,tanh), Lux.Dense(20,1)
)
p, st = Lux.setup(rng, ann)
```

And define the grey-box model, where I replace the `u[2]*u[2]` term with the output of the network. 

```
function GreyBox(u, p)
    z = ann(u, p, st)[1]
    [u[1].*u[1] .- params[1],
    z[1] .- params[2]]
end

NN_prob = NonlinearProblem{false}(GreyBox, guess, p)
NN_solution = solve(NN_prob NewtonRaphson())
```

In this case, `solve` isn't able to find the solution and the following error is returned.
```
ERROR: SingularException(2)
```

Was wondering if there would be a way to work around this issue.

**Comment by ChrisRackauckas** [comment]
What's the error message? Please share the whole message.

**Comment by CCsimon123** [comment]
I will make a PR tomorrow with a new `TrustRegion` solver to `NonlinearSolve.jl`
It will hopefully handle this by default, but I will make sure to test it!

**Comment by ChrisRackauckas** [comment]
Indeed, this is just because a standard Newton cannot handle the singularity, but trust region can.

```julia
using NonlinearSolve, Lux, LinearAlgebra, StableRNGs

rng = StableRNG(1111)

function func(u, p)
    [u[1].*u[1] .- p[1],
    u[2].*u[2] .- p[2]]
end

guess = [1., 1.]
params = [2.,3.]

prob = NonlinearProblem{false}(func, guess, params)
solution = solve(prob)

ann = Lux.Chain(
    Lux.Dense(2,20,tanh), Lux.Dense(20,20,tanh), Lux.Dense(20,1)
)
p, st = Lux.setup(rng, ann)

function GreyBox(u, p)
    z = ann(u, p, st)[1]
    [u[1].*u[1] .- params[1],
    z[1] .- params[2]]
end

NN_prob = NonlinearProblem{false}(GreyBox, guess, p)
NN_solution = solve(NN_prob)
```

this is fine with the default methods we have now, closing.
