### ISSUE TITLE
DF-Sane method

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#117]
https://www.rdocumentation.org/packages/BB/versions/2019.10-1/topics/dfsane
https://docs.scipy.org/doc/scipy/reference/optimize.root-dfsane.html

J Barzilai, and JM Borwein (1988), Two-point step size gradient methods, IMA J Numerical Analysis, 8, 141-148.

L Grippo, F Lampariello, and S Lucidi (1986), A nonmonotone line search technique for Newton's method, SIAM J on Numerical Analysis, 23, 707-716.

W LaCruz, JM Martinez, and M Raydan (2006), Spectral residual mathod without gradient information for solving large-scale nonlinear systems of equations, Mathematics of Computation, 75, 1429-1448.

R Varadhan and C Roland (2008), Simple and globally-convergent methods for accelerating the convergence of any EM algorithm, Scandinavian J Statistics.

R Varadhan and PD Gilbert (2009), BB: An R Package for Solving a Large System of Nonlinear Equations and for Optimizing a High-Dimensional Nonlinear Objective Function, J. Statistical Software, 32:4, http://www.jstatsoft.org/v32/i04/

**Comment by avik-pal** [comment]
Can be closed!
