### ISSUE TITLE
Double linear solve setups for Levenberg–Marquardt algorithm

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#133]
There are two separate linear solves, so it would be good to allow `linsolve` and `precs` for the two different ones, defaulting to using the same choice for the two. I don't know how helpful this would end up really being in practice, though for `iLU` you may want to cache different sparsities or something?

**Comment by avik-pal** [comment]
Is this needed though? The linear solves are $A x_1 = b_1$ and $A x_2 = b_2$. The original version using 2 distinct $A$s was an incorrect implementation that has been removed.
