### ISSUE TITLE
Turn off trust region when the iteration is stuck in local minima

### ISSUE THREAD

**Issue by YingboMa** [SciML/NonlinearSolve.jl#146]
Trust region is too conservative in the Freudenstein-Roth example
![freudenstein_roth](https://user-images.githubusercontent.com/17304743/217281467-7a92d57b-de37-4566-93f0-a50f4c66c38c.png)

**Comment by ChrisRackauckas** [comment]
Handled in https://github.com/SciML/NonlinearSolve.jl/pull/210
