### ISSUE TITLE
Documentation page missing

### ISSUE THREAD

**Issue by elbert5770** [SciML/NonlinearSolve.jl#147]
https://docs.sciml.ai/NonlinearSolve/stable/basics/solve/

**Comment by ChrisRackauckas** [comment]
Odd, the docstring exists

https://github.com/SciML/DiffEqBase.jl/blob/master/src/solve.jl#L831-L872

@ArnoStrouwen can you help investigate this?

**Comment by ArnoStrouwen** [comment]
Should this be true?
```
julia> supertype(supertype(NonlinearProblem))
SciMLBase.AbstractDEProblem
```

**Comment by ChrisRackauckas** [comment]
That's probably just a holdover from older times. It can probably be made to be a SciMLProblem that isn't an AbstractDEProblem, but the DiffEqBase/solve.jl would need to be updated for that.

**Comment by ArnoStrouwen** [comment]
Is this the one that should be there?
https://docs.sciml.ai/NonlinearSolve/dev/basics/solve/
I think it is confusing for the users that the CommonSolve is there.
They won't find the definition there.
Also the lack of a go to source button.

**Comment by ChrisRackauckas** [comment]
Yes dev looks fine.
