### ISSUE TITLE
TrustRegion is missing optimizations of using vjps directly

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#167]
https://github.com/SciML/NonlinearSolve.jl/pull/159/files/17abaf0801fb7e61f7a5fafbfb89c2266aec9f40#diff-d4ded13aeff73c93c2977a4227ff0ba4a434dc462ff8cc433761133aff882405

This can be computed using jvps to avoid the full Jacobian

**Comment by ChrisRackauckas** [comment]
@avik-pal was this handled?

**Comment by avik-pal** [comment]
Not yet. This is what @DavidKoplow is going to work on.

But it should be quite simple to do. The hackiest thing would be map `adjoint(::JacVec) -> VecJac` and remove some checks
