### ISSUE TITLE
Failing to Precompile NonLinearSolve.jl

### ISSUE THREAD

**Issue by AstitvaAggarwal** [SciML/NonlinearSolve.jl#176]
Im trying to use NeuralPDE which has a NonLinearSolve Dependancy and get the following errors.
Any Help is Appreciated, thanks.

(modandtest) pkg> st
Status `C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\modandtest\Project.toml`
  [587475ba] Flux v0.13.14
  [98e50ef6] JuliaFormatter v1.0.25
  [b2108857] Lux v0.4.49
  [961ee093] ModelingToolkit v8.51.0
  [315f7962] NeuralPDE v5.6.1 `..\NeuralPDE.jl`
  [7f7a1694] Optimization v3.13.0
  [36348300] OptimizationOptimJL v0.1.5
  [42dfb2eb] OptimizationOptimisers v0.1.2
  [1dea7af3] OrdinaryDiffEq v6.49.4
  [91a5bcdd] Plots v1.38.8
  [295af30f] Revise v3.5.2
  [fce5fe82] Turing v0.24.3
  [8dfed614] Test

julia> using NeuralPDE
[ Info: Precompiling NeuralPDE [315f7962-48a3-4962-8226-d0f33b1235f0]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6540d6a6 -- jl_unwrap_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1076 [inlined]
ijl_apply_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:954
in expression starting at C:\Users\astit\.julia\packages\NonlinearSolve\dQWiD\src\NonlinearSolve.jl:17
jl_unwrap_unionall at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:1076 [inlined]    
ijl_apply_type at /cygdrive/c/buildbot/worker/package_win64/build/src\jltypes.c:954
jl_deserialize_datatype at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:1498 [inlined]
jl_deserialize_value at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2195
jl_deserialize_value_method_instance at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:1807 [inlined]
jl_deserialize_value at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2142
jl_deserialize_value_array at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:1656
jl_deserialize_value at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2109
_jl_restore_incremental at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:3100
ijl_restore_incremental at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:3173
_include_from_serialized at .\loading.jl:807
_require_search_from_serialized at .\loading.jl:1039
_require at .\loading.jl:1315
_require_prelocked at .\loading.jl:1200
macro expansion at .\loading.jl:1180 [inlined]
macro expansion at .\lock.jl:223 [inlined]
require at .\loading.jl:1144
jfptr_require_55736.clone_1 at C:\Users\astit\AppData\Local\Programs\Julia-1.8.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1839 [inlined]
call_require at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:462 [inlined]
eval_import_path at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:499
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:725
jl_eval_module_expr at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:203 [inlined]
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:709
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:850
ijl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:915 [inlined]
ijl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:965
eval at .\boot.jl:368 [inlined]
include_string at .\loading.jl:1428
_include at .\loading.jl:1488
include at .\Base.jl:419 [inlined]
include_package_for_output at .\loading.jl:1554
jfptr_include_package_for_output_59041.clone_1 at C:\Users\astit\AppData\Local\Programs\Julia-1.8.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1839 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:126
eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:215
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:166 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:594
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:750
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:906
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:850
ijl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:915 [inlined]
ijl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:965
eval at .\boot.jl:368 [inlined]
include_string at .\loading.jl:1428
include_string at .\loading.jl:1438
exec_options at .\client.jl:301
_start at .\client.jl:522
jfptr__start_43806.clone_1 at C:\Users\astit\AppData\Local\Programs\Julia-1.8.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1839 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:575
jl_repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:719
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe.c:59
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 10660501 (Pool: 10657230; Big: 3271); GC: 6
ERROR: LoadError: Failed to precompile NonlinearSolve [8913a72c-1f9b-4ce2-8d82-65094dcecaec] to C:\Users\astit\.julia\compiled\v1.8\NonlinearSolve\jl_75B0.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:1707
  [3] compilecache
    @ .\loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1200
  [6] macro expansion
    @ .\loading.jl:1180 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1144
  [9] include
    @ .\Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\astit\.julia\packages\OrdinaryDiffEq\FttEX\src\OrdinaryDiffEq.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to C:\Users\astit\.julia\compiled\v1.8\OrdinaryDiffEq\jl_C81B.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:1707
  [3] compilecache
    @ .\loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1200
  [6] macro expansion
    @ .\loading.jl:1180 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1144
  [9] include
    @ .\Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\astit\.julia\packages\StochasticDiffEq\rZj4R\src\StochasticDiffEq.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile StochasticDiffEq [789caeaf-c7a9-5a7d-9973-96adeb23e2a0] to C:\Users\astit\.julia\compiled\v1.8\StochasticDiffEq\jl_86FB.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:1707
  [3] compilecache
    @ .\loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1200
  [6] macro expansion
    @ .\loading.jl:1180 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1144
  [9] include
    @ .\Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\NeuralPDE.jl\src\NeuralPDE.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile NeuralPDE [315f7962-48a3-4962-8226-d0f33b1235f0] to C:\Users\astit\.julia\compiled\v1.8\NeuralPDE\jl_CB0D.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:1707
  [3] compilecache
    @ .\loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1200
  [6] macro expansion
    @ .\loading.jl:1180 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1144
  [9] eval
    @ .\boot.jl:368 [inlined]
 [10] eval
    @ .\Base.jl:65 [inlined]
 [11] repleval(m::Module, code::Expr, #unused#::String)
    @ VSCodeServer c:\Users\astit\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:222
 [12] (::VSCodeServer.var"#107#109"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer c:\Users\astit\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:186
 [13] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:511
 [14] with_logger
    @ .\logging.jl:623 [inlined]
 [15] (::VSCodeServer.var"#106#108"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer c:\Users\astit\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:187
 [16] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [17] invokelatest(::Any)
    @ Base .\essentials.jl:726
 [18] macro expansion
    @ c:\Users\astit\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:34 [inlined]
 [19] (::VSCodeServer.var"#61#62")()
    @ VSCodeServer .\task.jl:484

**Comment by ChrisRackauckas** [comment]
Is this a standard Julia build from https://julialang.org/downloads/ ? Seems odd to be on v1.8.2: try v1.8.5?

**Comment by AstitvaAggarwal** [comment]
I fixed it by basically deleting my compiled directory in my .julia folder. Then started the Julia REPL again and executed  :         
] instantiate
