### ISSUE TITLE
Support for complex-values problems

### ISSUE THREAD

**Issue by lgravina1997** [SciML/NonlinearSolve.jl#177]
It seems that the present version does not support complex-valued problem. Let nlprob be a NonlinearProblem with uType Vector{ComplexF64}. Then 

solve(nlprob, NewtonRaphson(), abstol = 1e-9)

yields ArgumentError: Cannot create a dual over scalar type ComplexF64. If the type behaves as a scalar, define ForwardDiff.can_dual(::Type{ComplexF64}) = true.

Is there a way around this?

**Comment by avik-pal** [comment]
The default used to be ForwardDiff.jl but now we can do things smarter and chose the AD or Finite Diff based on the problem type. So this shouldn't be an issue!

**Comment by avik-pal** [comment]
This can be closed!
