### ISSUE TITLE
Inplace Problem Specification for Methods with `size(residual) != size(u)`

### ISSUE THREAD

**Issue by avik-pal** [SciML/NonlinearSolve.jl#195]
Currently, for inplace problems the residual vector is determined by the size of the input `u`. This is not necessarily correct for problems that support overconstrained / underconstrained setups. For example:
https://github.com/SciML/NonlinearSolve.jl/blob/691e10a25c0b20b3349770a4d54f93b41e5235a4/src/levenberg.jl#L269-L270

Could we potentially add a kwarg like `residual_size` which could be used to initialize this?

**Comment by ChrisRackauckas** [comment]
I think it may just be best to just use `jac_prototype` for this?

**Comment by avik-pal** [comment]
That seems like the proper solution. I will prototype this in NeuralBVP.jl and then port it over here.
