### ISSUE TITLE
Update README and docs tutorial examples to use new bracketing methods?

### ISSUE THREAD

**Issue by sjdaines** [SciML/NonlinearSolve.jl#209]
Currently the examples in [README.md ](https://github.com/SciML/SimpleNonlinearSolve.jl#readme)and https://docs.sciml.ai/NonlinearSolve/stable/tutorials/nonlinear/#Using-Bracketing-Methods 
still use the `Falsi` method which is not a good new user experience.

Suggest a better choice would be `Brent` ?

**Comment by ChrisRackauckas** [comment]
Fixed
