### ISSUE TITLE
Complete the iterator interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#241]
The iterator interface for NonlinearSolve.jl was never completed in the past, but it's very close. Next steps are:

- [ ] add dispatches for the common solve `step!` interface
- [ ] Setup the abstract caches as iterators that automatically iterate, and test with for loops
- [ ] Update the iterator interface page to showcase some uses, like in for loops https://docs.sciml.ai/NonlinearSolve/stable/tutorials/iterator_interface/

As inspiration, see https://docs.sciml.ai/DiffEqDocs/stable/basics/integrator/

**Comment by avik-pal** [comment]
This was done with 3.5 release
