### ISSUE TITLE
Implement Exciting-Mixing, Scalar and Diagonal Broyden approximations

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#260]
https://docs.scipy.org/doc/scipy/reference/optimize.root-excitingmixing.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.diagbroyden.html#scipy.optimize.diagbroyden
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linearmixing.html#scipy.optimize.linearmixing

**Comment by avik-pal** [comment]
LinearMixing is just `J = -1 / alpha`, and J is never updated, I don't think there is any point of having that, for small problems our Broyden operates in nanoseconds via StaticArrays and for larger problems this won't work anyways
