### ISSUE TITLE
Use DiffEqBase DEFAULT_LINSOLVE

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NonlinearSolve.jl#27]
This isn't quite possible because it would be a circular dependency, so we'd to do something a little trickier. But we should plan to keep the two swappable, and in the future find a way to share the same default.

**Comment by YingboMa** [comment]
Is this possible with SciMLBase?

**Comment by ChrisRackauckas** [comment]
Not really. It can't move to SciMLBase without taking all of RecursiveFactorization (LoopVectorization) and IterativeSolvers with it 🤷 so I'm just ignoring this detail for now.

**Comment by YingboMa** [comment]
Should we have SciMLBasicSolver.jl then?

**Comment by ChrisRackauckas** [comment]
```

Chris Rackauckas  10:50 AM
So basically:
All differential equation solvers are documented in DifferentialEquations.jl
All nonlinear solvers are documented in NonlinearSolve.jl
All optimization methods are documented in GalacticOptim.jl
All quadrature methods are documented in Quadrature.jl
```

what I left off what, so what do you want to do about `LinearProblem`? I think the answer should try to be the same here.

**Comment by ChrisRackauckas** [comment]
that change should happen at the same time as a redesign to allow LHL
