### ISSUE TITLE
Passing Jacobian to NLSolveJL

### ISSUE THREAD

**Issue by briochemc** [SciML/NonlinearSolve.jl#273]
Given `f` an `ODEFunction` (or a `NonlinearFunction`) with a Jacobian, how does one pass this Jacobian to the `NLSolveJL` solvers so that it does not try to autodiff it from `f`?

**Comment by avik-pal** [comment]
https://github.com/SciML/SciMLNLSolve.jl/blob/master/src/solve.jl#L67 it already does.

**Comment by briochemc** [comment]
Oops I'm just confused! I'll close this.
