### ISSUE TITLE
NonlinearSolve.jl not precompiling anymore

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/NonlinearSolve.jl#290]
My tests at ProbNumDiffEq.jl fail because NonlinearSolve.jl can not precompile anymore, which was not an issue some days ago. See this github action for a full stack trace:

https://github.com/nathanaelbosch/ProbNumDiffEq.jl/actions/runs/6956405592/job/18927191648?pr=269

**Comment by ChrisRackauckas** [comment]
What about upgrading to the patch hotfix v7.6.1?

**Comment by nathanaelbosch** [comment]
Works again, thanks for the fix.
