### ISSUE TITLE
Minor documentation problems

### ISSUE THREAD

**Issue by DavidSagan** [SciML/NonlinearSolve.jl#293]
- [ ] The READM.md examples are off. In both, the functions are `f(u,p)` but `prob` is set to `NonlinearProblem(f, u0)` and `IntervalNonlinearProblem(f, u0)` which lacks the `p` argument. Note: The corresponding examples in docs are correct.
- [ ] In the docs in the section [Problem Type 1: Solving Nonlinear Systems of Equations](https://docs.sciml.ai/NonlinearSolve/stable/tutorials/getting_started/#Problem-Type-1:-Solving-Nonlinear-Systems-of-Equations) it would be clearer if it was mentioned that the output of `f` needs to be the same length as the input `u`.
- [ ] In the section [The Three Types of Nonlinear Systems](https://docs.sciml.ai/NonlinearSolve/stable/tutorials/getting_started/#The-Three-Types-of-Nonlinear-Systems) there are actually four types. 
- [ ] It would help to have an example of a nonlinear least squares optimization.

**Comment by ChrisRackauckas** [comment]
> The READM.md examples are off. In both, the functions are f(u,p) but prob is set to NonlinearProblem(f, u0) and IntervalNonlinearProblem(f, u0) which lacks the p argument. Note: The corresponding examples in docs are correct.

The readme examples run fine. The `p` is optional in the problem type.

> It would help to have an example of a nonlinear least squares optimization.

Indeed this is a new feature and we need to get a tutorial for it.

**Comment by DavidSagan** [comment]
> The readme examples run fine. The p is optional in the problem type.

If the function was defined as `f(u; p)` then this would be correct but with `f(u, p)` the `p` argument is not optional.

Also I cannot seem to get a nonlinear least square optimization going. Can you post a simple example here? Thanks.

**Comment by ChrisRackauckas** [comment]
No in the problem type it's optional. It's not optional for `f`. It's just like all of the other problem types.

**Comment by avik-pal** [comment]
> Can you post a simple example here?

See this for now https://github.com/SciML/NonlinearSolve.jl/blob/master/test/nonlinear_least_squares.jl

**Comment by DavidSagan** [comment]
@avik-pal Much thanks! This is what I needed.

**Comment by ChrisRackauckas** [comment]
we still need a docs example
