### ISSUE TITLE
EnsembleProblem for NonlinearProblem

### ISSUE THREAD

**Issue by oameye** [SciML/NonlinearSolve.jl#365]
**Is your feature request related to a problem? Please describe.**

Solving `ODEProblem` for many initial conditions or a parameter sweep in with the `EnsembleProblem` feature in the OrdinaryDiffEq.jl package is really easy and can be parallelized really easily by choosing the `EnsembleAlg`.

**Describe the solution you’d like**

I would be nice to have the same features for `NonlinearProblem`

**Describe alternatives you’ve considered**

Now one can easily iterate the `solve` function with `remake`. However, the `EnsembleProblem` infrastructure makes this easy and performant. Another option would be using the `SteadyStateProblem` from SteadyStateDiffEq.jl package which works with EnsembleProblem. However, the `SteadyStateSolver` can be less performant.

**Comment by ChrisRackauckas** [comment]
Yup this is just a missing part of the interface.
