### ISSUE TITLE
Nolinearsolve returns error  for documentation example in Julia 1.10,1

### ISSUE THREAD

**Issue by ay111** [SciML/NonlinearSolve.jl#386]
Kindly see the error in the julia REPL shown below.

```julia
using NonlinearSolve

f(u, p) = u .* u .- p
# f (generic function with 1 method)

u0 = [1.0, 1.0]
p = 2.0

prob = NonlinearProblem(f, u0, p)

sol = solve(prob)
#=
ERROR: MethodError: no method matching init(::NonlinearProblem{…})

Closest candidates are:
  init(::OptimizationProblem, ::Any, ::Any...; kwargs...)
   @ SciMLBase C:\Users\adeto\.julia\packages\SciMLBase\QqtZA\src\solve.jl:144

Stacktrace:
 [1] solve(args::NonlinearProblem{…}; kwargs::@Kwargs{})
   @ CommonSolve C:\Users\adeto\.julia\packages\CommonSolve\JfpfI\src\CommonSolve.jl:23
 [2] top-level scope
   @ REPL[6]:1
Some type information was truncated. Use `show(err)` to see complete types.
=#
```

**Comment by avik-pal** [comment]
what version of NonlinearSolve are you using?

**Comment by ay111** [comment]
The version is 3.22. I update Julia every day but it refused to update it
to 3.73.

Regards.

**Comment by ChrisRackauckas** [comment]
Share `]st`

**Comment by ay111** [comment]
This is the screenshot of the status.

**Comment by avik-pal** [comment]
The screenshot didn't get added

**Comment by ay111** [comment]
See the attached screenshot.

**Comment by avik-pal** [comment]
github doesn't forward attachments of email.

**Comment by ay111** [comment]
Kindly send your email so that I can send it to you directly.

**Comment by avik-pal** [comment]
I had this error report from someone else as well, some packages are not updated and that pulls NonlinearSolve to `[8913a72c] NonlinearSolve v0.3.22`, note the "**v0.**". The current version is **v3**, so remove any package that is holding NonlinearSolve back and it should be fine.

**Comment by ay111** [comment]
I have removed the differentialequations, mittagleffler and some Packages
whose dependencies are preventing the update. Linear solve.jl is now
updated to the latest version.

I think Julia should allow multiple versions of packages to co-exist so
that one can call the latest version.

Thanks.

**Comment by ChrisRackauckas** [comment]
DifferentialEquations.jl is fine with the latest NonlinearSolve. mittagleffler looks fine as well.
