### ISSUE TITLE
Docs not found

### ISSUE THREAD

**Issue by metanoid** [SciML/NonlinearSolve.jl#39]
The "docs|stable" pill at the top of the README.md points to http://nonlinearsolve.sciml.ai/stable/, but this link does not exist, and gives a 404 error

**Comment by KronosTheLate** [comment]
Friendly reminder, still a problem

**Comment by ChrisRackauckas** [comment]
Hmm it probably needs a new minor for that to happen.

**Comment by ArnoStrouwen** [comment]
I think this is solved now?

**Comment by KronosTheLate** [comment]
Can confirm that the link works.
