### ISSUE TITLE
Consolidate `stats` handling

### ISSUE THREAD

**Issue by avik-pal** [SciML/NonlinearSolve.jl#410]
As pointed out by @oscardssmith, it would be good to store a centralized stats in the cache and update references to it instead of adding up the stats at the end.

Would probably make https://github.com/SciML/OrdinaryDiffEq.jl/pull/2167 easier

**Comment by oscardssmith** [comment]
Also worth noting that I'm pretty sure that for the polyalgs, the stats are just wrong. They appear to only report the stats from the solver that it actually used: https://github.com/SciML/NonlinearSolve.jl/blob/b389d0e9e9e4a1ff4350a2cce824ec8a03310e53/src/default.jl#L184C9-L184C14.
