### ISSUE TITLE
cache construction is no longer type stable

### ISSUE THREAD

**Issue by avik-pal** [SciML/NonlinearSolve.jl#469]
I will generate a MWE but the DI extras is not type stable, atleast in the bruss case I tested.

**Comment by gdalle** [comment]
That is unfortunately expected, as preparation implies choosing a chunk/batch size `B` and then putting seeds in batches with type `NTuple{B}`. It is a bit similar to ForwardDiff's preparation in that sense. I have opened https://github.com/gdalle/DifferentiationInterface.jl/issues/534 to keep track and brainstorm

**Comment by avik-pal** [comment]
In this case I was testing with a concrete chunksize specified. Without chunksize our code was type-unstable as well.

**Comment by gdalle** [comment]
On my way to fixing it

**Comment by gdalle** [comment]
Can you confirm that cache construction only used to be type-stable for sparse Jacobians? For dense Jacobians with ForwardDiff I don't see a way to get past `ForwardDiff.Chunk(x)`, which is type-unstable

**Comment by avik-pal** [comment]
For dense it used to be type stable if AutoForwardDiff had chunksize specified, else it would be type-unstable.

**Comment by gdalle** [comment]
Okay I need to look how you achieved type stability in the dense case. Can you point me to where that code lived?

**Comment by gdalle** [comment]
wait no I still don't have it, how do you statically set a chunk size while ensuring it always remains smaller than the vector length?

**Comment by avik-pal** [comment]
I think that case should be an error

**Comment by gdalle** [comment]
Alright I hadn't understood it that way.

**Comment by gdalle** [comment]
This issue should be fixed by [DI v0.6.5](https://github.com/gdalle/DifferentiationInterface.jl/releases/tag/DifferentiationInterface-v0.6.5), wanna check?
