### ISSUE TITLE
`NoColoringAlgorithm` not supported by DI yet

### ISSUE THREAD

**Issue by gdalle** [SciML/NonlinearSolve.jl#471]
I saw it in the big table of #468 and just wanted to warn you that it will fail in DI at the moment.
Have opened to keep track of the solution https://github.com/gdalle/SparseMatrixColorings.jl/issues/141

**Comment by avik-pal** [comment]
Right that just means we create a dense backend.

**Comment by gdalle** [comment]
I know, but since the creation of `NoColoringAlgorithm` we realized that these algorithms need to output a little more than just a vector of colors, so SparseMatrixColorings enforces a stronger interface. But I'm gonna add support for `NoColoringAlgorithm` in there

**Comment by gdalle** [comment]
Should be closed by https://github.com/gdalle/SparseMatrixColorings.jl/pull/142 even if you create a sparse backend with `NoColoringAlgorithm` (but that would be very inefficient)
