### ISSUE TITLE
Trying to add SciMLNLSolve results in an error

### ISSUE THREAD

**Issue by amrods** [SciML/NonlinearSolve.jl#48]
I am following the documentation here http://nonlinearsolve.sciml.ai/dev/solvers/NonlinearSystemSolvers/#SciMLNLSolve.jl but it results in an error:
```julia
(@v1.7) pkg> add SciMLNLSolve
    Updating registry at `~/.julia/registries/General.toml`
ERROR: The following package names could not be resolved:
 * SciMLNLSolve (not found in project, manifest or registry)
```

**Comment by ChrisRackauckas** [comment]
@utkarsh530 lets get some tests on here and get it released.

**Comment by ChrisRackauckas** [comment]
Registration started. https://github.com/JuliaRegistries/General/pull/52691 that takes 3 days for the first time. Cheers!
