### ISSUE TITLE
Support MVectors

### ISSUE THREAD

**Issue by amrods** [SciML/NonlinearSolve.jl#49]
see here:
https://discourse.julialang.org/t/help-with-nonlinearsolve-jl/74735

**Comment by ChrisRackauckas** [comment]
I'll handle this in a bit. There's two things here. One thing is that https://github.com/SciML/NonlinearSolve.jl/blob/master/src/scalar.jl we should make the scalar dispatch also support static arrays, that would be the direct fix to this issue. The other thing is that this repo needs to change from having an internal linear solver interface to using NonlinearSolve.jl
