### ISSUE TITLE
CITATION.cff and README recommend citing differently

### ISSUE THREAD

**Issue by ajwheeler** [SciML/NonlinearSolve.jl#493]
Just flagging that CITATION.cff is out of sync with the citation recommendation in the README.  I'm assuming you prefer we cite the paper on the arxiv?

Btw, thanks for the nice package.

**Comment by ChrisRackauckas** [comment]
Yes we should update that.

**Comment by avik-pal** [comment]
Thanks for pointing it out. I have updated it!
