### ISSUE TITLE
Newton trust region

### ISSUE THREAD

**Issue by YingboMa** [SciML/NonlinearSolve.jl#52]
Our `NewtonRaphson` implementation isn't robust against functions that look like this
![image](https://user-images.githubusercontent.com/17304743/153929846-a7a998ec-f35c-4cbc-ae2c-7e5f4950f5dc.png)

```julia
julia> nl(t, p) = 0.010000000000000002 + 10.000000000000002 / (1 + (0.21640425613334457 + 216.40425613334457 / (1 + (0.21640425613334457 + 216.40425613334457 / (1 + 0.0006250000000000001(t^2.0)))^2.0))^2.0) - 0.0011552453009332421t
nl (generic function with 2 methods)

julia> solve(NonlinearProblem(nl, 10.0), NewtonRaphson()).retcode
:MAXITERS_EXCEED
```

**Comment by ChrisRackauckas** [comment]
And note NLSolveJL does succeed here.

**Comment by CCsimon123** [comment]
I've implemented `trustRegion.jl` in `SimpleNonlinearSolve.jl` and I'll now give this a go.
(I've got exams coming, but I'll try to fix it asap)
