### ISSUE TITLE
[Docs] Stopping conditions

### ISSUE THREAD

**Issue by KronosTheLate** [SciML/NonlinearSolve.jl#64]
It would be nice to have a section in the documentation for different stopping conditions. The only way I was able to dig the information out was with `methods(solve)`.

Things that should be documented are (possibly incomplete list):
- [ ] maxiter
- [ ] tol
- [ ] atol
- [ ] rtol
- [ ] xatol
- [ ] xrtol

**Comment by ChrisRackauckas** [comment]
Note that those are "wrong". The namings need to match https://diffeq.sciml.ai/stable/basics/common_solver_opts/, so they won't be documented until they do.
