### ISSUE TITLE
wrap NLSolvers.jl?

### ISSUE THREAD

**Issue by briochemc** [SciML/NonlinearSolve.jl#75]
Maybe NonlinearSolve.jl should wrap https://github.com/JuliaNLSolvers/NLSolvers.jl?

**Comment by ChrisRackauckas** [comment]
Yes it's in the plan. The next library I'm going to do a massive update to is this one, after NeuralPDE is up to snuff and the LinearSolve.jl tutorials are fleshed out.

**Comment by oscardssmith** [comment]
this should be closed.

**Comment by ChrisRackauckas** [comment]
No it hasn't been done, but it probably won't be done.
