### ISSUE TITLE
`DEFAULT_PRECS` is not exported by NonlinearSolve

### ISSUE THREAD

**Issue by pkofod** [SciML/NonlinearSolve.jl#89]
In https://github.com/SciML/NonlinearSolve.jl/pull/86 you refer to `DEFAULT_PRECS` but that does not seem to be exported https://github.com/SciML/NonlinearSolve.jl/search?q=DEFAULT_PRECS . Found this in CI of another package.

**Comment by ChrisRackauckas** [comment]
Yes, I noticed this package was messed up when I saw the downstream failures. I'm cleaning it up in https://github.com/SciML/NonlinearSolve.jl/pull/88 and adding downstream tests.

**Comment by ChrisRackauckas** [comment]
The bad version was yanked.
